[theme]
# Customize the appearance further with font and background
base = "dark"
textColor = "#E0E0E0"
backgroundColor = "#141414"
secondaryBackgroundColor = "#222831"
primaryColor = "#00ADB5"
font = "monospace"


