[theme]
# Customize the appearance further with font and background
base = "dark"  # Or "light"
textColor = "#FFFFFF"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#2e2e2e"
primaryColor = "#3498db"
font = "sans-serif"


